import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer>
          <p className={'text-xs absolute bottom-0 right-2 text-gray footer'}>Font designed by Dimitri Antonov</p>
        </footer>
      </body>
    </html>
  );
}
